name: PR checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5


      - name: Setup environment
        run: |
           echo "UV_INDEX_HARBORN_USERNAME=harborn" >> $GITHUB_ENV
           echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV

      - name: Code Quality & Tests
        run: make ci

    env:
      DB_URL: ${{ secrets.DB_URL }}
